# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccaab9a2a5184434d8d5cf9260be95d41b7ad59e6a8a6c72c2e95ccc9504ec656bcc908b0c571cf04f80f7904bf09154b903780e415d702e35542d9690f07499

test:
  secret_key_base: 45422e2cabb14d9fb1a3fb62c8b79fe7809a86d83ba5eed287f301e76ec29f62a4859d1b63b9319038e109f63fdbb8668b824775e8f8c06348ea0da502fa0831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
